# Generated by Django 5.1.4 on 2025-08-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0044_appointment_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Welcome To Care Point', max_length=200)),
                ('subtitle', models.CharField(default='Choose well by choosing us.', max_length=200)),
                ('video_file', models.FileField(help_text='Upload MP4 video file', upload_to='banner_videos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banner Video',
                'verbose_name_plural': 'Banner Videos',
            },
        ),
    ]
