# Generated by Django 5.1.4 on 2025-09-12 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0045_bannervideo'),
    ]

    operations = [
    ]
