# Generated by Django 5.1.4 on 2025-09-12 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0046_auto_20250912_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.prescription'),
        ),
    ]
